import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCityWeather1725788381698 implements MigrationInterface {
    name = 'AddCityWeather1725788381698'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_flight" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "origin" varchar NOT NULL, "destination" varchar NOT NULL, "airline" varchar NOT NULL, "flight_num" integer NOT NULL, "origin_iata_code" varchar NOT NULL, "origin_name" varchar NOT NULL, "origin_latitude" decimal(10,7) NOT NULL, "origin_longitude" decimal(10,7) NOT NULL, "destination_iata_code" varchar NOT NULL, "destination_name" varchar NOT NULL, "destination_latitude" decimal(10,7) NOT NULL, "destination_longitude" decimal(10,7) NOT NULL, "originCityWeatherId" integer, "destinationCityWeatherId" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_flight"("id", "origin", "destination", "airline", "flight_num", "origin_iata_code", "origin_name", "origin_latitude", "origin_longitude", "destination_iata_code", "destination_name", "destination_latitude", "destination_longitude") SELECT "id", "origin", "destination", "airline", "flight_num", "origin_iata_code", "origin_name", "origin_latitude", "origin_longitude", "destination_iata_code", "destination_name", "destination_latitude", "destination_longitude" FROM "flight"`);
        await queryRunner.query(`DROP TABLE "flight"`);
        await queryRunner.query(`ALTER TABLE "temporary_flight" RENAME TO "flight"`);
        await queryRunner.query(`CREATE TABLE "temporary_flight" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "origin" varchar NOT NULL, "destination" varchar NOT NULL, "airline" varchar NOT NULL, "flight_num" integer NOT NULL, "origin_iata_code" varchar NOT NULL, "origin_name" varchar NOT NULL, "origin_latitude" decimal(10,7) NOT NULL, "origin_longitude" decimal(10,7) NOT NULL, "destination_iata_code" varchar NOT NULL, "destination_name" varchar NOT NULL, "destination_latitude" decimal(10,7) NOT NULL, "destination_longitude" decimal(10,7) NOT NULL, "originCityWeatherId" integer, "destinationCityWeatherId" integer, CONSTRAINT "FK_7a6060dfc740ceb2331b4d6bcdf" FOREIGN KEY ("originCityWeatherId") REFERENCES "city_weather" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_cce2b34265d388481790f347823" FOREIGN KEY ("destinationCityWeatherId") REFERENCES "city_weather" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_flight"("id", "origin", "destination", "airline", "flight_num", "origin_iata_code", "origin_name", "origin_latitude", "origin_longitude", "destination_iata_code", "destination_name", "destination_latitude", "destination_longitude", "originCityWeatherId", "destinationCityWeatherId") SELECT "id", "origin", "destination", "airline", "flight_num", "origin_iata_code", "origin_name", "origin_latitude", "origin_longitude", "destination_iata_code", "destination_name", "destination_latitude", "destination_longitude", "originCityWeatherId", "destinationCityWeatherId" FROM "flight"`);
        await queryRunner.query(`DROP TABLE "flight"`);
        await queryRunner.query(`ALTER TABLE "temporary_flight" RENAME TO "flight"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "flight" RENAME TO "temporary_flight"`);
        await queryRunner.query(`CREATE TABLE "flight" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "origin" varchar NOT NULL, "destination" varchar NOT NULL, "airline" varchar NOT NULL, "flight_num" integer NOT NULL, "origin_iata_code" varchar NOT NULL, "origin_name" varchar NOT NULL, "origin_latitude" decimal(10,7) NOT NULL, "origin_longitude" decimal(10,7) NOT NULL, "destination_iata_code" varchar NOT NULL, "destination_name" varchar NOT NULL, "destination_latitude" decimal(10,7) NOT NULL, "destination_longitude" decimal(10,7) NOT NULL, "originCityWeatherId" integer, "destinationCityWeatherId" integer)`);
        await queryRunner.query(`INSERT INTO "flight"("id", "origin", "destination", "airline", "flight_num", "origin_iata_code", "origin_name", "origin_latitude", "origin_longitude", "destination_iata_code", "destination_name", "destination_latitude", "destination_longitude", "originCityWeatherId", "destinationCityWeatherId") SELECT "id", "origin", "destination", "airline", "flight_num", "origin_iata_code", "origin_name", "origin_latitude", "origin_longitude", "destination_iata_code", "destination_name", "destination_latitude", "destination_longitude", "originCityWeatherId", "destinationCityWeatherId" FROM "temporary_flight"`);
        await queryRunner.query(`DROP TABLE "temporary_flight"`);
        await queryRunner.query(`ALTER TABLE "flight" RENAME TO "temporary_flight"`);
        await queryRunner.query(`CREATE TABLE "flight" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "origin" varchar NOT NULL, "destination" varchar NOT NULL, "airline" varchar NOT NULL, "flight_num" integer NOT NULL, "origin_iata_code" varchar NOT NULL, "origin_name" varchar NOT NULL, "origin_latitude" decimal(10,7) NOT NULL, "origin_longitude" decimal(10,7) NOT NULL, "destination_iata_code" varchar NOT NULL, "destination_name" varchar NOT NULL, "destination_latitude" decimal(10,7) NOT NULL, "destination_longitude" decimal(10,7) NOT NULL)`);
        await queryRunner.query(`INSERT INTO "flight"("id", "origin", "destination", "airline", "flight_num", "origin_iata_code", "origin_name", "origin_latitude", "origin_longitude", "destination_iata_code", "destination_name", "destination_latitude", "destination_longitude") SELECT "id", "origin", "destination", "airline", "flight_num", "origin_iata_code", "origin_name", "origin_latitude", "origin_longitude", "destination_iata_code", "destination_name", "destination_latitude", "destination_longitude" FROM "temporary_flight"`);
        await queryRunner.query(`DROP TABLE "temporary_flight"`);
    }

}
